name: 'Deploy'
on: 
    - repository_dispatch
jobs:
    sites-squads:
        name: 'sites-squads'
        runs-on: [self-hosted]
        steps:
          - name: 'terraform plan'
            run: echo terraform plan
          - name: 'terraform apply'
            run: echo terraform apply
          - name: 'configure'
            run: echo configure
    
    sites-pre-prod:
        name: 'sites-pre-prod'
        runs-on: [self-hosted]
        needs:  [sites-squads]
        steps:
          - name: 'terraform plan'
            run: echo terraform plan
          - name: 'terraform apply'
            run: echo terraform apply
          - name: 'configure'
            run: echo configure
    
    sites-cust-1:
        name: 'sites-cust-1'
        runs-on: [self-hosted]
        needs:  [sites-pre-prod]
        steps:
          - name: 'terraform plan'
            run: echo terraform plan
          - name: 'terraform apply'
            run: echo terraform apply
          - name: 'configure'
            run: echo configure
    
    sites-cust-2:
        name: 'sites-cust-2'
        runs-on: [self-hosted]
        needs:  [sites-pre-prod]
        steps:
          - name: 'terraform plan'
            run: echo terraform plan
          - name: 'terraform apply'
            run: echo terraform apply
          - name: 'configure'
            run: echo configure